AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infrastructure/cognito.yaml

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infrastructure/database.yaml

  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: infrastructure/api-gateway.yaml

  PostServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: post-service/template.yaml